# Generated by Django 6.0.6 on 2026-06-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'familias',
                'ordering': ['titulo'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('alias', models.CharField(blank=True, max_length=200, null=True)),
                ('stock', models.IntegerField()),
                ('imagen', models.CharField(blank=True, max_length=200, null=True)),
                ('habilitado', models.IntegerField()),
                ('eliminado', models.IntegerField()),
                ('historico', models.IntegerField()),
            ],
            options={
                'db_table': 'productos',
                'ordering': ['titulo'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoGrupo',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'productos_grupo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoMedida',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'productos_medida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=30, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'proveedores',
                'ordering': ['marca'],
                'managed': False,
            },
        ),
    ]
