# Generated by Django 6.0.6 on 2026-06-17 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_catalogo', models.ImageField(blank=True, null=True, upload_to='catalogo/')),
                ('descripcion_catalogo', models.TextField(blank=True, null=True)),
                ('especificaciones', models.TextField(blank=True, null=True)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('orden_catalogo', models.IntegerField(default=0)),
                ('visible_catalogo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catalogo', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Producto Catálogo',
                'verbose_name_plural': 'Productos Catálogo',
                'ordering': ['orden_catalogo', 'producto__titulo'],
            },
        ),
    ]
